[project]
name = "trflow"
version = "0.0.1"
description = "Helper functions for performing a variety of tandem repeat analysis tasks"
authors = [
    { name = "Egor Dolzhenko", email = "edolzhenko@pacificbiosciences.com" },
]
